

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rssagg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  

  # redis:
  #   image: redis:7
  #   container_name: my_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  pgdata:
