// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (url, title, description, site_url)
VALUES ($1, $2, $3, $4)
RETURNING id, title, url, last_fetched_at, created_at, site_url, description
`

type CreateFeedParams struct {
	Url         string      `json:"url"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	SiteUrl     pgtype.Text `json:"site_url"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.SiteUrl,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.SiteUrl,
		&i.Description,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, title, url, last_fetched_at, created_at, site_url, description FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.SiteUrl,
		&i.Description,
	)
	return i, err
}
