// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	FeedUrl       string             `json:"feed_url"`
	WebsiteUrl    string             `json:"website_url"`
	Description   sql.NullString     `json:"description"`
	LastFetchedAt pgtype.Timestamptz `json:"last_fetched_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Post struct {
	ID          int32          `json:"id"`
	FeedID      int32          `json:"feed_id"`
	Title       string         `json:"title"`
	Url         string         `json:"url"`
	Description sql.NullString `json:"description"`
	PublishedAt time.Time      `json:"published_at"`
	Guid        string         `json:"guid"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	AuthType     string    `json:"auth_type"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserFeed struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	FeedID    int32     `json:"feed_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserPost struct {
	UserID     int32     `json:"user_id"`
	PostID     int32     `json:"post_id"`
	IsRead     bool      `json:"is_read"`
	IsFavorite bool      `json:"is_favorite"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
