// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	FeedUrl       string             `json:"feed_url"`
	WebsiteUrl    string             `json:"website_url"`
	Description   pgtype.Text        `json:"description"`
	LastFetchedAt pgtype.Timestamptz `json:"last_fetched_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type Post struct {
	ID          int32       `json:"id"`
	FeedID      int32       `json:"feed_id"`
	Title       string      `json:"title"`
	Url         string      `json:"url"`
	Description pgtype.Text `json:"description"`
	PublishedAt time.Time   `json:"published_at"`
	Guid        pgtype.Text `json:"guid"`
	CreatedAt   time.Time   `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	AuthType     string    `json:"auth_type"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserFeed struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	FeedID    int32     `json:"feed_id"`
	CreatedAt time.Time `json:"created_at"`
}
