// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (UserFeed, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllFeedsByUserID(ctx context.Context, userID int32) error
	DeleteFeedByID(ctx context.Context, id int32) error
	DeleteFeedIfUnused(ctx context.Context, id int32) error
	GetAllFeeds(ctx context.Context) ([]Feed, error)
	GetAllPosts(ctx context.Context) ([]Post, error)
	GetFavoritePostsByUser(ctx context.Context, arg GetFavoritePostsByUserParams) ([]Post, error)
	GetFeedByID(ctx context.Context, id int32) (Feed, error)
	GetFeedURLByID(ctx context.Context, id int32) (string, error)
	GetFeedsByUserID(ctx context.Context, userID int32) ([]Feed, error)
	GetLatestPosts(ctx context.Context, limit int32) ([]Post, error)
	GetPostByID(ctx context.Context, id int32) (Post, error)
	GetPostsByFeedID(ctx context.Context, feedID int32) ([]Post, error)
	GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]Post, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserPostState(ctx context.Context, arg GetUserPostStateParams) (UserPost, error)
	GetUserSubscribedFeeds(ctx context.Context, userID int32) ([]Feed, error)
	MarkPostFavorite(ctx context.Context, arg MarkPostFavoriteParams) error
	MarkPostRead(ctx context.Context, arg MarkPostReadParams) error
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error)
	UnsubscribeUserFromFeed(ctx context.Context, arg UnsubscribeUserFromFeedParams) error
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpdateFeedFetchTime(ctx context.Context, arg UpdateFeedFetchTimeParams) (Feed, error)
	UpsertUserPostState(ctx context.Context, arg UpsertUserPostStateParams) error
}

var _ Querier = (*Queries)(nil)
