// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (UserFeed, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllFeedsByUserID(ctx context.Context, userID int32) error
	DeleteFeedByID(ctx context.Context, id int32) error
	DeleteFeedIfUnused(ctx context.Context, id int32) error
	GetAllFeeds(ctx context.Context) ([]Feed, error)
	GetAllPosts(ctx context.Context) ([]Post, error)
	GetFeedByID(ctx context.Context, id int32) (Feed, error)
	GetFeedURLByID(ctx context.Context, id int32) (string, error)
	GetFeedsByUserID(ctx context.Context, userID int32) ([]Feed, error)
	GetPostByID(ctx context.Context, id int32) (Post, error)
	GetPostsByFeedID(ctx context.Context, feedID int32) ([]Post, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error)
	UpdateFeedFetchTime(ctx context.Context, arg UpdateFeedFetchTimeParams) (Feed, error)
}

var _ Querier = (*Queries)(nil)
