// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package repo

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO user_feeds(user_id, feed_id)
VALUES ($1, $2)
RETURNING id, user_id, feed_id, created_at
`

type CreateSubscriptionParams struct {
	UserID int32 `json:"user_id"`
	FeedID int32 `json:"feed_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (UserFeed, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.FeedID)
	var i UserFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
	)
	return i, err
}
