// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Title         string             `json:"title"`
	Url           string             `json:"url"`
	LastFetchedAt pgtype.Timestamptz `json:"last_fetched_at"`
}

type Post struct {
	ID          pgtype.UUID        `json:"id"`
	FeedID      pgtype.UUID        `json:"feed_id"`
	Title       string             `json:"title"`
	Url         string             `json:"url"`
	Description pgtype.Text        `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	Guid        string             `json:"guid"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserFeed struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FeedID    pgtype.UUID        `json:"feed_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserPostStatus struct {
	UserID     pgtype.UUID `json:"user_id"`
	PostID     pgtype.UUID `json:"post_id"`
	IsRead     bool        `json:"is_read"`
	IsFavorite bool        `json:"is_favorite"`
}
